// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QServe.Data;

#nullable disable

namespace QServe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QServe.Models.AuditLog", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.HasIndex("PerformedBy");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("QServe.Models.MenuCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MenuCategories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Beverages"
                        },
                        new
                        {
                            CategoryID = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Starters"
                        },
                        new
                        {
                            CategoryID = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Main Course"
                        });
                });

            modelBuilder.Entity("QServe.Models.MenuItem", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RecentOrdered")
                        .HasColumnType("int");

                    b.Property<int>("TotalOrdered")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("CategoryID");

                    b.ToTable("MenuItems", t =>
                        {
                            t.HasCheckConstraint("CK_MenuItems_ItemType", "\"ItemType\" IN ('Beverage','Cooked','Dessert','Quick')");

                            t.HasCheckConstraint("CK_MenuItems_Price", "\"Price\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Masala Chai",
                            PrepTimeMinutes = 5,
                            Price = 40m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 2,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Fresh Lime Soda",
                            PrepTimeMinutes = 5,
                            Price = 60m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 3,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Cold Coffee",
                            PrepTimeMinutes = 5,
                            Price = 90m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 4,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "Veg Spring Rolls",
                            PrepTimeMinutes = 10,
                            Price = 150m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 5,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Chicken Satay",
                            PrepTimeMinutes = 15,
                            Price = 220m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 6,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Paneer Butter Masala",
                            PrepTimeMinutes = 20,
                            Price = 260m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 7,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Chicken Biryani",
                            PrepTimeMinutes = 25,
                            Price = 320m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 8,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Grilled Fish",
                            PrepTimeMinutes = 22,
                            Price = 380m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 9,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Dessert",
                            Name = "Gulab Jamun",
                            PrepTimeMinutes = 5,
                            Price = 90m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 10,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Dessert",
                            Name = "Chocolate Brownie",
                            PrepTimeMinutes = 8,
                            Price = 140m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 11,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Mango Juice",
                            PrepTimeMinutes = 5,
                            Price = 80m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 12,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Watermelon Juice",
                            PrepTimeMinutes = 5,
                            Price = 70m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 13,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Iced Tea",
                            PrepTimeMinutes = 5,
                            Price = 75m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 14,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "French Fries",
                            PrepTimeMinutes = 10,
                            Price = 120m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 15,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "Veg Burger",
                            PrepTimeMinutes = 12,
                            Price = 160m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 16,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "Chicken Burger",
                            PrepTimeMinutes = 15,
                            Price = 190m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 17,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1562967914-608f82629710?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "Chicken Nuggets",
                            PrepTimeMinutes = 12,
                            Price = 180m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 18,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Veg Fried Rice",
                            PrepTimeMinutes = 18,
                            Price = 180m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 19,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Chicken Fried Rice",
                            PrepTimeMinutes = 20,
                            Price = 240m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 20,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1552611052-33e04de081de?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Veg Noodles",
                            PrepTimeMinutes = 15,
                            Price = 170m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 22,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Butter Chicken",
                            PrepTimeMinutes = 25,
                            Price = 340m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 23,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Dessert",
                            Name = "Chocolate Ice Cream",
                            PrepTimeMinutes = 3,
                            Price = 110m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 24,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Dessert",
                            Name = "Vanilla Ice Cream",
                            PrepTimeMinutes = 3,
                            Price = 100m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 25,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Dessert",
                            Name = "Cheesecake",
                            PrepTimeMinutes = 8,
                            Price = 180m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 26,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Masala Buttermilk",
                            PrepTimeMinutes = 3,
                            Price = 50m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 27,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1626201850125-18d2d9a17c5b?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Sweet Lassi",
                            PrepTimeMinutes = 5,
                            Price = 80m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 28,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Mango Lassi",
                            PrepTimeMinutes = 5,
                            Price = 100m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 29,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "Samosa",
                            PrepTimeMinutes = 8,
                            Price = 60m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 30,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "Paneer Tikka",
                            PrepTimeMinutes = 15,
                            Price = 220m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 31,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "Chicken 65",
                            PrepTimeMinutes = 15,
                            Price = 240m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 32,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "Vegetable Pakora",
                            PrepTimeMinutes = 10,
                            Price = 100m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 33,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd5?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "Kerala Parotta",
                            PrepTimeMinutes = 5,
                            Price = 20m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 34,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Kadai Paneer",
                            PrepTimeMinutes = 20,
                            Price = 280m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 35,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Palak Paneer",
                            PrepTimeMinutes = 20,
                            Price = 260m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 36,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Chicken Curry",
                            PrepTimeMinutes = 25,
                            Price = 280m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 37,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1625944525945-7d8b40f95f69?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Kerala Fish Curry",
                            PrepTimeMinutes = 25,
                            Price = 300m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 38,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1545247181-516773cae754?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Mutton Rogan Josh",
                            PrepTimeMinutes = 30,
                            Price = 420m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 39,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Appam with Chicken Stew",
                            PrepTimeMinutes = 20,
                            Price = 250m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 40,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Dessert",
                            Name = "Payasam",
                            PrepTimeMinutes = 5,
                            Price = 100m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 41,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            ItemType = "Dessert",
                            Name = "Rasgulla",
                            PrepTimeMinutes = 5,
                            Price = 90m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        });
                });

            modelBuilder.Entity("QServe.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ServedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("TableID");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_OrderStatus", "\"OrderStatus\" IN ('PendingPayment','AwaitingVerification','Approved','Preparing','Ready','Served','Cancelled')");

                            t.HasCheckConstraint("CK_Orders_OrderType", "\"OrderType\" IN ('Quick','Regular','Heavy')");

                            t.HasCheckConstraint("CK_Orders_TotalAmount", "\"TotalAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("QServe.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<string>("Customization")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderItemID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("QServe.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RazorpayOrderID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazorpayPaymentID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("VerificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_PaymentMode", "\"PaymentMode\" IN ('Online','Cash','Card')");

                            t.HasCheckConstraint("CK_Payments_PaymentStatus", "\"PaymentStatus\" IN ('Pending','Processing','Received','Failed','Refunded')");
                        });
                });

            modelBuilder.Entity("QServe.Models.RestaurantTable", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QRCodeData")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TableID");

                    b.HasIndex("TableNumber")
                        .IsUnique();

                    b.ToTable("RestaurantTables", t =>
                        {
                            t.HasCheckConstraint("CK_RestaurantTables_Capacity", "\"Capacity\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            TableID = 1,
                            Capacity = 4,
                            IsActive = true,
                            QRCodeData = "",
                            TableNumber = "T01"
                        },
                        new
                        {
                            TableID = 2,
                            Capacity = 4,
                            IsActive = true,
                            QRCodeData = "",
                            TableNumber = "T02"
                        },
                        new
                        {
                            TableID = 3,
                            Capacity = 4,
                            IsActive = true,
                            QRCodeData = "",
                            TableNumber = "T03"
                        },
                        new
                        {
                            TableID = 4,
                            Capacity = 4,
                            IsActive = true,
                            QRCodeData = "",
                            TableNumber = "T04"
                        },
                        new
                        {
                            TableID = 5,
                            Capacity = 4,
                            IsActive = true,
                            QRCodeData = "",
                            TableNumber = "T05"
                        });
                });

            modelBuilder.Entity("QServe.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Admin','Kitchen','Manager')");
                        });

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@restaurant.local",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$QMyrjjsBLb7obUvnOtfbiu.H5O0IrMWVqsAOCG0OS4xuUkUsj/ct2",
                            Role = "Admin"
                        },
                        new
                        {
                            UserID = 2,
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kitchen@restaurant.local",
                            FullName = "Kitchen Staff",
                            IsActive = true,
                            PasswordHash = "$2a$11$iXo607uYZzXx9Lves8pkEeihb0WrXiAYfO0ka./e1.hKTKt3T554W",
                            Role = "Kitchen"
                        },
                        new
                        {
                            UserID = 3,
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager@restaurant.local",
                            FullName = "Restaurant Manager",
                            IsActive = true,
                            PasswordHash = "$2a$11$GQqWprbnqdgn/88W318q1.CIMOKhOgJYQo9F.wij6ERJMS4H5hgve",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("QServe.Models.AuditLog", b =>
                {
                    b.HasOne("QServe.Models.User", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("QServe.Models.MenuItem", b =>
                {
                    b.HasOne("QServe.Models.MenuCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QServe.Models.Order", b =>
                {
                    b.HasOne("QServe.Models.RestaurantTable", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("QServe.Models.OrderItem", b =>
                {
                    b.HasOne("QServe.Models.MenuItem", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QServe.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QServe.Models.Payment", b =>
                {
                    b.HasOne("QServe.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QServe.Models.User", "VerifiedByUser")
                        .WithMany("VerifiedPayments")
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("QServe.Models.MenuCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QServe.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("QServe.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("QServe.Models.RestaurantTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("QServe.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("VerifiedPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
