// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QServe.Data;

#nullable disable

namespace QServe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QServe.Models.AuditLog", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.HasIndex("PerformedBy");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("QServe.Models.MenuCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MenuCategories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Beverages"
                        },
                        new
                        {
                            CategoryID = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Starters"
                        },
                        new
                        {
                            CategoryID = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Main Course"
                        });
                });

            modelBuilder.Entity("QServe.Models.MenuItem", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RecentOrdered")
                        .HasColumnType("int");

                    b.Property<int>("TotalOrdered")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("CategoryID");

                    b.ToTable("MenuItems", t =>
                        {
                            t.HasCheckConstraint("CK_MenuItems_ItemType", "\"ItemType\" IN ('Beverage','Cooked','Dessert','Quick')");

                            t.HasCheckConstraint("CK_MenuItems_Price", "\"Price\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Masala Chai",
                            PrepTimeMinutes = 5,
                            Price = 40m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 2,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Fresh Lime Soda",
                            PrepTimeMinutes = 5,
                            Price = 60m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 3,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            ItemType = "Beverage",
                            Name = "Cold Coffee",
                            PrepTimeMinutes = 5,
                            Price = 90m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 4,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            ItemType = "Quick",
                            Name = "Veg Spring Rolls",
                            PrepTimeMinutes = 10,
                            Price = 150m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 5,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Chicken Satay",
                            PrepTimeMinutes = 15,
                            Price = 220m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 6,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Paneer Butter Masala",
                            PrepTimeMinutes = 20,
                            Price = 260m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 7,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Chicken Biryani",
                            PrepTimeMinutes = 25,
                            Price = 320m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 8,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            ItemType = "Cooked",
                            Name = "Grilled Fish",
                            PrepTimeMinutes = 22,
                            Price = 380m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 9,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            ItemType = "Dessert",
                            Name = "Gulab Jamun",
                            PrepTimeMinutes = 5,
                            Price = 90m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        },
                        new
                        {
                            ItemID = 10,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            ItemType = "Dessert",
                            Name = "Chocolate Brownie",
                            PrepTimeMinutes = 8,
                            Price = 140m,
                            RecentOrdered = 0,
                            TotalOrdered = 0
                        });
                });

            modelBuilder.Entity("QServe.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ServedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("TableID");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_OrderStatus", "\"OrderStatus\" IN ('PendingPayment','AwaitingVerification','Approved','Preparing','Ready','Served','Cancelled')");

                            t.HasCheckConstraint("CK_Orders_OrderType", "\"OrderType\" IN ('Quick','Regular','Heavy')");

                            t.HasCheckConstraint("CK_Orders_TotalAmount", "\"TotalAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("QServe.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<string>("Customization")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderItemID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("QServe.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RazorpayOrderID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazorpayPaymentID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("VerificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.HasIndex("VerifiedBy");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_PaymentMode", "\"PaymentMode\" IN ('Online','Cash','Card')");

                            t.HasCheckConstraint("CK_Payments_PaymentStatus", "\"PaymentStatus\" IN ('Pending','Processing','Received','Failed','Refunded')");
                        });
                });

            modelBuilder.Entity("QServe.Models.RestaurantTable", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QRCodeData")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TableID");

                    b.HasIndex("TableNumber")
                        .IsUnique();

                    b.ToTable("RestaurantTables", t =>
                        {
                            t.HasCheckConstraint("CK_RestaurantTables_Capacity", "\"Capacity\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            TableID = 1,
                            Capacity = 4,
                            IsActive = true,
                            QRCodeData = "https://localhost/order/table/1",
                            TableNumber = "T01"
                        },
                        new
                        {
                            TableID = 2,
                            Capacity = 4,
                            IsActive = true,
                            QRCodeData = "https://localhost/order/table/2",
                            TableNumber = "T02"
                        },
                        new
                        {
                            TableID = 3,
                            Capacity = 4,
                            IsActive = true,
                            QRCodeData = "https://localhost/order/table/3",
                            TableNumber = "T03"
                        },
                        new
                        {
                            TableID = 4,
                            Capacity = 4,
                            IsActive = true,
                            QRCodeData = "https://localhost/order/table/4",
                            TableNumber = "T04"
                        },
                        new
                        {
                            TableID = 5,
                            Capacity = 4,
                            IsActive = true,
                            QRCodeData = "https://localhost/order/table/5",
                            TableNumber = "T05"
                        });
                });

            modelBuilder.Entity("QServe.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Admin','Kitchen','Manager')");
                        });

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@restaurant.local",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$qeuWfT3Trc9jwgc/c1wiuu976WqXO.Ky7vkyDPXbC8yp49IQW5svi",
                            Role = "Admin"
                        },
                        new
                        {
                            UserID = 2,
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kitchen@restaurant.local",
                            FullName = "Kitchen Staff",
                            IsActive = true,
                            PasswordHash = "$2a$11$r/EF2qcOpYImHhRJ/gPanO4wjQQLubCc98GFRmkTl5pCFpZs3GAGG",
                            Role = "Kitchen"
                        },
                        new
                        {
                            UserID = 3,
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager@restaurant.local",
                            FullName = "Restaurant Manager",
                            IsActive = true,
                            PasswordHash = "$2a$11$rwv6qCoAlVJavgawV22e7.HXpQ0dM4sPFpyF7squOu1YKFXOs6JZO",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("QServe.Models.AuditLog", b =>
                {
                    b.HasOne("QServe.Models.User", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("QServe.Models.MenuItem", b =>
                {
                    b.HasOne("QServe.Models.MenuCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QServe.Models.Order", b =>
                {
                    b.HasOne("QServe.Models.RestaurantTable", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("QServe.Models.OrderItem", b =>
                {
                    b.HasOne("QServe.Models.MenuItem", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QServe.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("QServe.Models.Payment", b =>
                {
                    b.HasOne("QServe.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("QServe.Models.Payment", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QServe.Models.User", "VerifiedByUser")
                        .WithMany("VerifiedPayments")
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("QServe.Models.MenuCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QServe.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("QServe.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("QServe.Models.RestaurantTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("QServe.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("VerifiedPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
